enum ActionTypes {
    GET_JOBS_REQUEST = 'GET_JOBS_REQUEST',
    GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS',
    GET_JOBS_FAIL = 'GET_JOBS_FAIL',

    GET_JOBS_PAPE_COUNT = 'GET_JOBS_PAPE_COUNT',
    GET_JOBS_PAPE_COUNT_SUCCESS = 'GET_JOBS_PAPE_COUNT_SUCCESS',
    GET_JOBS_PAPE_COUNT_FAIL = 'GET_JOBS_PAPE_COUNT_FAIL',
}

export default ActionTypes;